/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class DataCounterJp extends javax.swing.JPanel {

    /**
     * Creates new form DataCounterJp
     * @param pathi
     * @throws java.io.IOException
     */
    public DataCounterJp(String pathi) throws IOException {
	this.pathi = pathi;
	initComponents();
	llogarit();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("DataCounter"), "Data Counter"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Column Name", "#No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    String pathi;
    final void llogarit() throws IOException{
	ArrayList<String> headers;
	ArrayList<String> fields;
	
	packages.CsvReader sr = new packages.CsvReader();
	BufferedReader bfr = new BufferedReader(new FileReader(pathi));
	headers = sr.lineSplitter(bfr.readLine());
	int[] counter = new int[headers.size()];
	String line;
	int i = 0;
	while((line = bfr.readLine()) != null)
	{
	    if(i == 0){}
	    else{
		fields = sr.lineSplitter(line);
		int a = 0;
		for(String s:fields)
		{
		    if(s.trim().length() > 0)
			counter[a]++;
		    a++;
		}
	    }
	    i++;
	}
	ArrayList<String> llogarit = new ArrayList();
	for(int c = 0; c < counter.length; c++)
	    llogarit.add(c, counter[c]+"");

	DefaultTableModel modeli = new DefaultTableModel();
	modeli.addColumn("Column name", headers.toArray());
	modeli.addColumn("#No", llogarit.toArray());
	jTable1.setModel(modeli);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
